name: cd

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  docker:
    runs-on: ubuntu-latest
    needs: [ golangci ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker metadata-action
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: robsonpeixoto/echo-server
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      pull-requests: write
    needs: [golangci, docker]
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: go
          package-name: github.com/robsonpeixoto/echo-server
