name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

permissions:
  contents: write
  pull-requests: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        if: github.event_name == 'pull_request'
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: golangci-lint
        if: github.event_name == 'pull_request'
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Docker metadata-action
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: robsonpeixoto/echo-server
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: google-github-actions/release-please-action@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          release-type: go
          package-name: github.com/robsonpeixoto/echo-server
